#!/usr/bin/env babel-node
import koa from 'koa'
import sendfile from 'koa-sendfile'
import serve from 'koa-static'

let app = koa()
app.use(serve(__dirname))
app.use(catchAll)
app.listen(3000)

function *catchAll(next) {
  var stats = yield* sendfile.call(this, `${__dirname}/index.html`)
  if (!this.status) this.throw(404)
}
